#######################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  elasticsearch:
    rest:
      uris: "db:9200"
  data:
    elasticsearch:
      cluster-nodes: "db:9300"
      cluster-name: "docker-cluster"
